{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.severity('blocker')\n    @allure.feature('模块3：xxxxx')\n    @allure.issue('http://49.235.92.12:8080/zentao/bug-view-1.html')\n    def test_02():\n        '''用例2的描述：222222'''\n        print('测试用例2')\n>       assert 1==2\nE       assert 1 == 2\n\ntest_x.py:22: AssertionError"}, "description": "用例2的描述：222222", "attachments": [{"name": "stdout", "source": "0e0d1681-0ece-46d9-b4bc-7b40bbd4bdfe-attachment.txt", "type": "text/plain"}], "start": 1595695535717, "stop": 1595695535717, "uuid": "b9cd555a-1055-4050-959c-ea269c18a9bc", "historyId": "c35b4053dcc909fd2ca3bb5e94bc7f0a", "testCaseId": "af921dd42851a9658f1251a37fcdd915", "fullName": "test_x#test_02", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "模块3：xxxxx"}, {"name": "suite", "value": "test_x"}, {"name": "host", "value": "kingving"}, {"name": "thread", "value": "24208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_x"}], "links": [{"type": "issue", "url": "http://49.235.92.12:8080/zentao/bug-view-1.html", "name": "http://49.235.92.12:8080/zentao/bug-view-1.html"}]}