{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.severity('blocker')\n    @allure.feature('模块3：xxxxx')\n    @allure.issue('http://49.235.92.12:8080/zentao/bug-view-1.html')\n    def test_02():\n        '''用例2的描述：222222'''\n        print('测试用例2')\n>       assert 1==2\nE       assert 1 == 2\n\ntest_x.py:22: AssertionError"}, "description": "用例2的描述：222222", "attachments": [{"name": "stdout", "source": "a50d18e3-106f-4194-9ffc-24b6b5adfdd4-attachment.txt", "type": "text/plain"}], "start": 1595699717459, "stop": 1595699717460, "uuid": "b1e7d6db-64a4-495a-a16c-42bb26d881ed", "historyId": "c35b4053dcc909fd2ca3bb5e94bc7f0a", "testCaseId": "af921dd42851a9658f1251a37fcdd915", "fullName": "test_x#test_02", "labels": [{"name": "feature", "value": "模块3：xxxxx"}, {"name": "severity", "value": "blocker"}, {"name": "suite", "value": "test_x"}, {"name": "host", "value": "kingving"}, {"name": "thread", "value": "14056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_x"}], "links": [{"type": "issue", "url": "http://49.235.92.12:8080/zentao/bug-view-1.html", "name": "http://49.235.92.12:8080/zentao/bug-view-1.html"}]}